# -*- coding: utf-8 -*-
{
    'name': 'Library Management',
    'version': '18.0.1.1.4',
    'author': 'Jay Butani',
    'sequence': 5,
    'summary': 'Library Management Module',
    'description': "LMS",
    'website': 'https://www.aktivsoftware.com',
    'data': [
        'security/library_security.xml',
        'security/ir.model.access.csv',
        'report/ir_actions_report.xml',
        'report/ir_actions_report_templates.xml',
        'report/report_custom_invoice.xml',
        'data/ir_sequence_data.xml',
        'data/ir_cron_data.xml',
        'data/mail_template_data.xml',
        'views/library_book_views.xml',
        'views/library_members_views.xml',
        'views/library_book_tags_views.xml',
        'views/library_book_category_views.xml',
        'views/library_book_location_views.xml',
        'views/product_template_views.xml',
        'views/product_template_barcode_views.xml',
        'views/sale_menus.xml',
        'views/library_bulk_book_views.xml',
        'views/res_users_views.xml',
        'views/sale_order_views.xml',
        'wizard/sale_order_check_quantity_wizard_views.xml',
        'views/res_partner_views.xml',
        'views/borrow_transaction_history_views.xml',
        'wizard/borrow_transaction_history_wizard_views.xml',
        'views/stock_warehouse_views.xml',
        'views/res_config_settings_views.xml',
        'views/res_partner_custom_template.xml',
        'views/contacts_menu.xml'
    ],
    'assets': {
        'web.assets_frontend': ['ak_library_management/static/src/js/contact_webcontroller.js']
    },
    'depends':['sale_management','contacts','stock','base_automation','hr','website'],
    'application': True,
    'license': 'LGPL-3',
}
